### ISSUE TITLE
Assigning Hospital or University to Speciality Orgs

### ISSUE THREAD

**Issue by olbeck** [Nonprofit-Open-Data-Collective/mission-taxonomies#1]
Do we want to assign "TRUE" hospital or university values for specialty orgs whose further categorization is a hospital or university? 

For example, E0221. Should this be marked as hospital or no? It is a specialty org since the first two digits are "02" but it is for a hospital since the last two digits are "21". 

Another example, B0342. Should this be marked as a university since the further categorization of the last two digits are "42". 

See [NTEE disaggregation crosswalk data](https://github.com/Nonprofit-Open-Data-Collective/mission-taxonomies/blob/main/NTEE-disaggregated/ntee-crosswalk.csv) for more examples.

**Comment by lecy** [comment]
I think it would be advocacy org for hospitals specifically, right? 

So no, it would not have any of the characteristics of a hospital that would make it a good comparison. 

I suspect the same for a professional association for universities. What would that be, something like the Chronicle for Higher Ed or a professional association like American Economics Association?

**Comment by olbeck** [comment]
Fixed so that `hosp` and `univ` depend on `two.digit`, not `two.digit.s`.
